package model.pojos;
// Generated 9-ago-2012 18.23.18 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

    private int idlog;
    private Store store;
    private Date instanttime;
    private String executor;
    private String activity;
    private boolean result;

    public Log() {
    }

    public Log(int idlog, Store store, Date instanttime, String executor, String activity, boolean result) {
        this.idlog = idlog;
        this.store = store;
        this.instanttime = instanttime;
        this.executor = executor;
        this.activity = activity;
        this.result = result;
    }

    public int getIdlog() {
        return this.idlog;
    }

    public void setIdlog(int idlog) {
        this.idlog = idlog;
    }

    public Store getStore() {
        return this.store;
    }

    public void setStore(Store store) {
        this.store = store;
    }

    public Date getInstanttime() {
        return this.instanttime;
    }

    public void setInstanttime(Date instanttime) {
        this.instanttime = instanttime;
    }

    public String getExecutor() {
        return this.executor;
    }

    public void setExecutor(String executor) {
        this.executor = executor;
    }

    public String getActivity() {
        return this.activity;
    }

    public void setActivity(String activity) {
        this.activity = activity;
    }

    public boolean isResult() {
        return this.result;
    }

    public void setResult(boolean result) {
        this.result = result;
    }

    @Override
    public String toString() {
        return instanttime + " (" + executor + "-" + activity + ")";
    }
}
