package model.pojos;
// Generated 9-ago-2012 18.23.18 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Lot generated by hbm2java
 */
public class Lot implements java.io.Serializable {

    private Integer idlot;
    private Product product;
    private String barcode;
    private int quantity;
    private Date expiration;

    public Lot() {
    }

    public Lot(Product product, String barcode, int quantity, Date expiration) {
        this.product = product;
        this.barcode = barcode;
        this.quantity = quantity;
        this.expiration = expiration;
    }

    public Integer getIdlot() {
        return this.idlot;
    }

    public void setIdlot(Integer idlot) {
        this.idlot = idlot;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public Date getExpiration() {
        return this.expiration;
    }

    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }

    @Override
    public String toString() {
        return barcode + " (" + quantity + ")";
    }
}
