package model.pojos;
// Generated 9-ago-2012 18.23.18 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

    private Integer idproduct;
    private Store store;
    private String brand;
    private String type;
    private int totstored;
    private int totrequested;
    private int totsold;
    private int totexpired;
    private int totreturned;
    private int tempstored;
    private int temprequested;
    private int tempsold;
    private int tempexpired;
    private int tempreturned;
    private Set<Lot> lots = new HashSet<Lot>(0);

    public Product() {
    }

    public Product(Store store, String type, int totstored, int totrequested, int totsold, int totexpired, int totreturned, int tempstored, int temprequested, int tempsold, int tempexpired, int tempreturned) {
        this.store = store;
        this.type = type;
        this.totstored = totstored;
        this.totrequested = totrequested;
        this.totsold = totsold;
        this.totexpired = totexpired;
        this.totreturned = totreturned;
        this.tempstored = tempstored;
        this.temprequested = temprequested;
        this.tempsold = tempsold;
        this.tempexpired = tempexpired;
        this.tempreturned = tempreturned;
    }

    public Product(Store store, String brand, String type, int totstored, int totrequested, int totsold, int totexpired, int totreturned, int tempstored, int temprequested, int tempsold, int tempexpired, int tempreturned, Set<Lot> lots) {
        this.store = store;
        this.brand = brand;
        this.type = type;
        this.totstored = totstored;
        this.totrequested = totrequested;
        this.totsold = totsold;
        this.totexpired = totexpired;
        this.totreturned = totreturned;
        this.tempstored = tempstored;
        this.temprequested = temprequested;
        this.tempsold = tempsold;
        this.tempexpired = tempexpired;
        this.tempreturned = tempreturned;
        this.lots = lots;
    }

    public Integer getIdproduct() {
        return this.idproduct;
    }

    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }

    public Store getStore() {
        return this.store;
    }

    public void setStore(Store store) {
        this.store = store;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getTotstored() {
        return this.totstored;
    }

    public void setTotstored(int totstored) {
        this.totstored = totstored;
    }

    public int getTotrequested() {
        return this.totrequested;
    }

    public void setTotrequested(int totrequested) {
        this.totrequested = totrequested;
    }

    public int getTotsold() {
        return this.totsold;
    }

    public void setTotsold(int totsold) {
        this.totsold = totsold;
    }

    public int getTotexpired() {
        return this.totexpired;
    }

    public void setTotexpired(int totexpired) {
        this.totexpired = totexpired;
    }

    public int getTotreturned() {
        return this.totreturned;
    }

    public void setTotreturned(int totreturned) {
        this.totreturned = totreturned;
    }

    public int getTempstored() {
        return this.tempstored;
    }

    public void setTempstored(int tempstored) {
        this.tempstored = tempstored;
    }

    public int getTemprequested() {
        return this.temprequested;
    }

    public void setTemprequested(int temprequested) {
        this.temprequested = temprequested;
    }

    public int getTempsold() {
        return this.tempsold;
    }

    public void setTempsold(int tempsold) {
        this.tempsold = tempsold;
    }

    public int getTempexpired() {
        return this.tempexpired;
    }

    public void setTempexpired(int tempexpired) {
        this.tempexpired = tempexpired;
    }

    public int getTempreturned() {
        return this.tempreturned;
    }

    public void setTempreturned(int tempreturned) {
        this.tempreturned = tempreturned;
    }

    @XmlTransient
    public Set<Lot> getLots() {
        return this.lots;
    }

    public void setLots(Set<Lot> lots) {
        this.lots = lots;
    }

    @Override
    public String toString() {
        return brand + " " + type;
    }
}
