package model.pojos;
// Generated 9-ago-2012 18.23.18 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

    private Integer idrole;
    private String name;
    private Boolean generaladministrator;
    private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

    public Role(String name) {
        this.name = name;
    }

    public Role(String name, Boolean generaladministrator, Set<User> users) {
        this.name = name;
        this.generaladministrator = generaladministrator;
        this.users = users;
    }

    public Integer getIdrole() {
        return this.idrole;
    }

    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean isGeneraladministrator() {
        return this.generaladministrator;
    }

    public void setGeneraladministrator(Boolean generaladministrator) {
        this.generaladministrator = generaladministrator;
    }

    @XmlTransient
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @Override
    public String toString() {
        return name;
    }
}
