package model.pojos;
// Generated 9-ago-2012 18.23.18 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer iduser;
    private Store store;
    private Role role;
    private String login;
    private String password;
    private String namesurname;
    private String email;
    private Date pwexpiration;
    private Date regexpiration;
    private Integer sessionduration;

    public User() {
    }

    public User(Role role, String login, String password, String email) {
        this.role = role;
        this.login = login;
        this.password = password;
        this.email = email;
    }

    public User(Store store, Role role, String login, String password, String namesurname, String email, Date pwexpiration, Date regexpiration, Integer sessionduration) {
        this.store = store;
        this.role = role;
        this.login = login;
        this.password = password;
        this.namesurname = namesurname;
        this.email = email;
        this.pwexpiration = pwexpiration;
        this.regexpiration = regexpiration;
        this.sessionduration = sessionduration;
    }

    public Integer getIduser() {
        return this.iduser;
    }

    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    public Store getStore() {
        return this.store;
    }

    public void setStore(Store store) {
        this.store = store;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNamesurname() {
        return this.namesurname;
    }

    public void setNamesurname(String namesurname) {
        this.namesurname = namesurname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getPwexpiration() {
        return this.pwexpiration;
    }

    public void setPwexpiration(Date pwexpiration) {
        this.pwexpiration = pwexpiration;
    }

    public Date getRegexpiration() {
        return this.regexpiration;
    }

    public void setRegexpiration(Date regexpiration) {
        this.regexpiration = regexpiration;
    }

    public Integer getSessionduration() {
        return this.sessionduration;
    }

    public void setSessionduration(Integer sessionduration) {
        this.sessionduration = sessionduration;
    }

    @Override
    public String toString() {
        return login + " (" + namesurname + ")";
    }
}
